md \HABLA.330
md \HABLA.330\BH
md \HABLA.330\CIBER
md \HABLA.330\ENPCH
md \HABLA.330\PCH
md \HABLA.330\PARLA
copy \asm\bh\habla.com    \habla.330\bh\habla.com
copy \asm\ciber\habla.com \habla.330\ciber\habla.com
copy \asm\parla\habla.com \habla.330\parla\h5.com
copy \asm\parla\habla.bat \habla.330\parla\habla.bat
copy \asm\parla\ttse.dif \habla.330\parla\ttse.dif
copy \asm\parla\ttse.grm \habla.330\parla\ttse.grm
copy \asm\parla\ttsebox.exe \habla.330\parla\ttsebox.exe
copy \asm\pch\habla.com   \habla.330\pch\habla.com
copy \asm\enpch\habla.com \habla.330\enpch\habla.com